[package]
name = "unplugged-mic-notification"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4"
cpal = "0.13"
rodio = "0.15.0"
cli_select = "0.1.3"
chrono = "0.4"